---
# vars file for Dokuwiki

# Répertoire de l'applications
Path_Directory: "/srv/www/htdocs"
# Répertoire Source
Path_Source: "/root/dokuwiki"
Path_Conf: "/etc/apache2/httpd.conf"
# Nom de l'application à vérifier
Ligne_1: "AddHandler application/x-httpd-php72 .php .php5 .php4 .php3"
Ligne_After_1: "IncludeOptional /etc/apache2/vhosts.d/*.conf"
Ligne_2: "AddHandler php7-script .php"
Ligne_After_2: "AddHandler application/x-httpd-php72 .php .php5 .php4 .php3"
Ligne_3: "AddType application/x-httpd-php .php"
Ligne_After_3: "AddHandler php7-script .php"
Application_user: "wwwrun"
Application_group: "root"
# nom des modules complémentaires pour apache
application_modules_apache:
- "rewrite"
Package_apache: "apache2"
Package_php: "php7"
application_name: OMIS
application_version: 1.1.0
application_type: PHP7 et APACHE2
