---
# tasks file for DeploiAPP

   - name: Create Directory Date Livraison
     become: yes
     file:
       path: "/root/Livraisons/iStdstand/{{ansible_date_time.date|replace('-','')}}"
       state: directory

   - name: Copier le fichier tar sur livraison
     become: yes
     copy: 
       src: /home/sau/
       dest: /root/Livraisons/iStdstand/{{ansible_date_time.date|replace('-','') }}
       remote_src: yes

   - name: Suppression du contenu du rép iStdstand
     become: yes
     shell: rm -rf /srv/www/htdocs/iStdtand/*

     #- name: Vérifier les sources de Livraison
     #become: yes
     #shell : ls -lrt /Livraisons/iStdstand/{{ansible_date_time.date|replace('-','')}}
     #register: liste

     #- debug:
     #msg: "{{ liste }}"

   - name: Check Suppression Du rép iStdstand
     become: yes
     shell: ls -lrt /srv/www/htdocs/iStdtand/
     register: CheckSupp

   - debug:
       msg: "Le contenu du Répertoire a été supprimé {{ CheckSupp.stdout_lines }}"


   - name: Décompresser le contenu de fichier Tar & Copier sur l'APP iStdtand
     become: yes
     #ignore_errors: yes
     unarchive:
        src: /root/Livraisons/iStdstand/{{ansible_date_time.date|replace('-','') }}/Std-Test.tar
        dest: /root/Livraisons/iStdstand/{{ansible_date_time.date|replace('-','') }}
        remote_src: yes
        #shell: tar -xvf /root/Livraisons/iStdstand/{{ansible_date_time.date|replace('-','') }}/Std-Test.tar -C /srv/www/htdocs/iStdtand/
     register: checkk
     ignore_errors: True

   - name: Copier des sources applicative
     become: yes
     copy:
      src: /root/Livraisons/iStdstand/{{ansible_date_time.date|replace('-','') }}/{{ item }}/
      dest: /srv/www/htdocs/iStdtand/ 
      remote_src: yes
      directory_mode: yes
     with_items:
       - src

     # - debug:
     # msg: "Le fichier est décompressé et copier sur l'APP iStdtandi"
     # when: checkk.rc==0

   - name: Check Contenue  Du rép iStdstand
     become: yes
     shell: ls -lrt /srv/www/htdocs/iStdtand/
     register: CheckContenu

   - debug:
       msg: "{{ CheckContenu.stdout_lines }}"

   - name: Droit propriétaire  de l'APP istdstand
     become: yes
     #file:
     #dest: "/srv/www/htdocs/iStdtand/"
       #state: touch
       #owner: wwwrun
       # group: root
     command: chown -R wwwrun:root /srv/www/htdocs/iStdtand
 
