---
# tasks file for Create_vm

- name: Create a virtual machine on given ESXi hostname
  vmware_guest:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    validate_certs: no
    datacenter: "{{ datacenter }}"
    folder: Datacenter1/vm 
    name: "{{ vm_name }}"
    state: poweredoff
    guest_id: centos64Guest
    # This is hostname of particular ESXi server on which user wants VM to be deployed
    esxi_hostname: "{{ esxi_hostname }}"
    disk:
    - size_gb: "{{ disk }}" 
      type: thin
      datastore: "{{ datastore }}"
    hardware:
      memory_mb: "{{ vm_ram }}"
      num_cpus: "{{ vm_cpus }}"
      scsi: "{{ vm_scsi }}"
    networks:
    - name: VM Network 
    #  netmask: 255.255.255.0
      device_type: "{{ type_net }}"
   # wait_for_ip_address: yes
    #template: Sles15
    #state: powerdon
  delegate_to: localhost
  register: deploy_vm


- debug:
    msg: "{{ deploy_vm }}"

